kind: Secret
apiVersion: v1
metadata:
  name: api-internal-gateway-v2
  namespace: linkapi
data:
  DSN: >-
    bW9uZ29kYjovL2FkbWluX3BhcmFtZXRyaXphdGlvbnM6aHVzVWZyRjlzNnlzSlV6WkBsa3AtcHJvZC1wYXJhbWV0cml6YXRpb25zLXNoYXJkLTAwLTAwLXBja2NvLmF6dXJlLm1vbmdvZGIubmV0OjI3MDE3LGxrcC1wcm9kLXBhcmFtZXRyaXphdGlvbnMtc2hhcmQtMDAtMDEtcGNrY28uYXp1cmUubW9uZ29kYi5uZXQ6MjcwMTcsbGtwLXByb2QtcGFyYW1ldHJpemF0aW9ucy1zaGFyZC0wMC0wMi1wY2tjby5henVyZS5tb25nb2RiLm5ldDoyNzAxNy9sa3BfcHJvZD9yZXBsaWNhU2V0PUxLUC1QUk9ELVBBUkFNRVRSSVpBVElPTlMtc2hhcmQtMCZhdXRoU291cmNlPWFkbWluJnJlYWRQcmVmZXJlbmNlPXByaW1hcnkmc3NsPXRydWU=
  TOKEN: ZXlKMGVYQWlPaUpLVjFRaUw=
type: Opaque
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: api-internal-gateway-v2
  namespace: linkapi
data:
  ENVIRONMENT: PRODUCTION
  PORT: "50051"
---
kind: Service
apiVersion: v1
metadata:
  name: api-internal-gateway-v2
  namespace: linkapi
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
  selector:
    run: api-internal-gateway-v2
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-internal-gateway-v2
spec:
  selector:
    matchLabels:
      run: api-internal-gateway-v2
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: api-internal-gateway-v2
    spec:
      nodeSelector:
        node_subnet: private
      containers:
        - image: IMAGE_NAME
          name: api-internal-gateway-v2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: api-internal-gateway-v2
            - secretRef:
                name: api-internal-gateway-v2
          ports:
            - containerPort: 50051
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 100m
      imagePullSecrets:
        - name: dockerhub
      volumes:
        - name: repositories
          emptyDir: {}
